sudo: required
language: node_js
services:
  - docker
addons:
  apt:
    packages:
      - docker-ce
notifications:
    slack: youcanbenefit:${SLACK_CHANNEL1}
branches:
  only:
    - master
before_install:
  - docker --version
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
script:
  - ./build/build.sh frontend backend --push