# Docker image
# Build a Docker image to deploy, run, or push to a container registry.
# Add steps that use Docker Compose, tag images, push to a registry, run an image, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
  branches:
    include:
    - master
pr: none

pool:
  vmImage: 'Ubuntu-16.04'

steps:
- bash: |
    cd backend
    npm ci
    npm run unit-test
  displayName: 'docker unit-test backend'

- bash: |
    cd backend
    docker build --tag $(registryServerName)/youcanbenefit-api:$(build.buildId) --tag $(registryServerName)/youcanbenefit-api:latest .
  displayName: 'docker build backend'

- bash: |
    cd frontend
    docker build --tag $(registryServerName)/youcanbenefit-web:$(build.buildId) --tag $(registryServerName)/youcanbenefit-web:latest .
  displayName: 'docker build frontend'

- bash: echo $(docker.password) | docker login -u $(docker.username) --password-stdin
  displayName: 'docker login'

- bash: |
    docker push $(registryServerName)/youcanbenefit-api:$(build.buildId)
    docker push $(registryServerName)/youcanbenefit-api:latest
  displayName: 'docker push backend'

- bash: |
    docker push $(registryServerName)/youcanbenefit-web:$(build.buildId)
    docker push $(registryServerName)/youcanbenefit-web:latest
  displayName: 'docker push frontend'
